WIDTH = 1440
HEIGHT = 720
GRID_SIZE = 6
CELL_COUNT = GRID_SIZE ** 2
MINES_COUNT = (CELL_COUNT) // 10
CELL_HEIGHT = 4
CELL_WIDTH = 12


'''# Easy
EASY_GRID_SIZE = 6
EASY_CELL_COUNT = GRID_SIZE ** 2
EASY_MINES_COUNT = (CELL_COUNT) // 10
CELL_HEIGHT = 4
CELL_WIDTH = 12

# Medium
MEDIUM_GRID_SIZE = 10
MEDIUM_CELL_COUNT = GRID_SIZE ** 2
MEDIUM_MINES_COUNT = (CELL_COUNT) // 6
CELL_HEIGHT = 3
CELL_WIDTH = 9

# Hard
HARD_GRID_SIZE = 14
HARD_CELL_COUNT = GRID_SIZE ** 2
HARD_MINES_COUNT = (CELL_COUNT) // 4
CELL_HEIGHT = 2
CELL_WIDTH = 6
'''